feat: Complete implementation
The previous commit was generated and it wasn't working at all.
This one basically corrects and extends generated code to provide
working asdf plugin.

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -1,23 +1,84 @@
 #!/usr/bin/env bash
 
+#
+#  Usage as standalone:
+#    ASDF_INSTALL_VERSION=1.6.0-alpha2 ASDF_DOWNLOAD_PATH=tmp-downloads ./bin/download
+#
+#  To see debug logs use env var `DEBUG=true`.
+#
+
 set -euo pipefail
 
-current_script_path=${BASH_SOURCE[0]}
-plugin_dir=$(dirname "$(dirname "$current_script_path")")
+CURRENT_SCRIPT_PATH=${BASH_SOURCE[0]}
+PLUGIN_DIR=$(dirname "$(dirname "$CURRENT_SCRIPT_PATH")")
 
-# shellcheck source=./lib/utils.bash
-source "${plugin_dir}/lib/utils.bash"
+# shellcheck source=./lib/common.bash
+source "${PLUGIN_DIR}/lib/common.bash" # GH_REPO
+# shellcheck source=./lib/log.bash
+source "${PLUGIN_DIR}/lib/log.bash" # log_debug log_info is_debug
+# shellcheck source=./lib/trap.bash
+source "${PLUGIN_DIR}/lib/trap.bash" # add_on_exit
 
-mkdir -p "$ASDF_DOWNLOAD_PATH"
+download_release() {
+  local version="$1"
+  local dest="$2"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+  local platform_uname platform
+  platform_uname="$(uname -s)"
+  case "${platform_uname}" in
+    Linux*) platform="linux" ;;
+    Darwin*) platform="darwin" ;;
+    *) fail "Platform \"${platform_uname}\" is not yet supported." ;;
+  esac
 
-# Download tar.gz file to the download directory
-download_release "$ASDF_INSTALL_VERSION" "$release_file"
+  local uname_arch arch
+  uname_arch="$(uname -m)"
+  case "${uname_arch}" in
+    arm) arch="arm" ;;
+    aarch64 | arm64) arch="arm64" ;;
+    x86_64) arch="amd64" ;;
+    i*86) arch="386" ;;
+    *) fail "Architecture \"${uname_arch}\" is not yet supported." ;;
+  esac
+  # possible values:
+  # https://stackoverflow.com/questions/45125516/possible-values-for-uname-m
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+  local temp_dir
+  temp_dir=$(mktemp -d -t "asdf-opentofu.XXXX")
+  add_on_exit rm -rf "${temp_dir}"
 
-# Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
+  log_info "* Downloading opentofu release ${version}..."
+
+  # releases: https://github.com/opentofu/opentofu/releases
+  # sample URL: https://github.com/opentofu/opentofu/releases/download/v1.6.0-alpha2/tofu_1.6.0-alpha2_linux_amd64.zip
+  local download_url="${GH_REPO}/releases/download/v${version}/tofu_${version}_${platform}_${arch}.zip"
+  log_info "from ${download_url}"
+
+  local curl_opts=(-fsSL)
+  if [ -n "${GITHUB_API_TOKEN:-}" ]; then
+    curl_opts=("${curl_opts[@]}" -H "Authorization: token $GITHUB_API_TOKEN")
+  fi
+
+  local temp_zip_path="${temp_dir}/tofu.zip"
+  curl "${curl_opts[@]}" -o "${temp_zip_path}" -C - "${download_url}" || fail "Could not download ${download_url}"
+
+  local unzip_opts=(-o "${temp_zip_path}" -d "${dest}")
+  ! is_debug && unzip_opts=(-q "${unzip_opts[@]}")
+  unzip "${unzip_opts[@]}" || fail "Could not extract ${temp_zip_path}"
+
+  log_info "* Downloading opentofu release ${version}... DONE"
+}
+
+main() {
+  [ -z "${ASDF_DOWNLOAD_PATH+x}" ] && fail "ASDF_DOWNLOAD_PATH is required"
+  [ -z "${ASDF_INSTALL_VERSION+x}" ] && fail "ASDF_INSTALL_VERSION is required"
+
+  log_debug "ASDF_DOWNLOAD_PATH: $ASDF_DOWNLOAD_PATH"
+  log_debug "ASDF_INSTALL_VERSION: $ASDF_INSTALL_VERSION"
+  log_debug "TOOL_NAME: $TOOL_NAME"
+
+  mkdir -p "$ASDF_DOWNLOAD_PATH"
+  download_release "${ASDF_INSTALL_VERSION}" "${ASDF_DOWNLOAD_PATH}"
+}
+
+main "$@"
